<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
    </actionOverrides>
    <formFactors>Small</formFactors>
    <formFactors>Medium</formFactors>
    <formFactors>Large</formFactors>
    <label>Sales</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>ReadOnly</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>SolutionManager</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Perfil Banca Personas</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>MarketingProfile</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>High Volume Customer Portal User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Chatter External User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Chatter Free User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Chatter Moderator User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>Prueba_QA_Record_Page</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>QA_Test_Cases__c</pageOrSobjectType>
        <recordType>QA_Test_Cases__c.QA_test_cases</recordType>
        <type>Flexipage</type>
        <profile>Usuario estándard personalizado</profile>
    </profileActionOverrides>
    <tab>standard-home</tab>
    <tab>standard-Opportunity</tab>
    <tab>standard-Lead</tab>
    <tab>standard-Task</tab>
    <tab>standard-File</tab>
    <tab>standard-ContentNote</tab>
    <tab>standard-Account</tab>
    <tab>standard-Contact</tab>
    <tab>standard-Campaign</tab>
    <tab>standard-Dashboard</tab>
    <tab>standard-report</tab>
    <tab>standard-Feed</tab>
    <tab>standard-CollaborationGroup</tab>
    <tab>standard-Event</tab>
    <tab>standard-OtherUserProfile</tab>
    <tab>standard-Case</tab>
    <tab>standard-News</tab>
    <tab>standard-Forecasting3</tab>
    <tab>QA_Test_Cases__c</tab>
    <uiType>Lightning</uiType>
</CustomApplication>
