/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ADM_CreateCommentAction {
    global ADM_CreateCommentAction() {

    }
    webService static List<agf__ADM_Comment__c> get(String value) {
        return null;
    }
}
