/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ADM_WorkRemoteActionsExtension {
    @RemoteAction
    global static String calculatePriority(Id frequencyID, Id impactID) {
        return null;
    }
    @RemoteAction
    global static agf.ADM_WorkAssignment.AssignmentContext getAssignments(String severityLevel, agf__ADM_Product_Tag__c productTag, RecordType recordType, String workType, String recipients) {
        return null;
    }
    @RemoteAction
    global static void setWorkPanelViewPreference(Boolean toggleValue) {

    }
}
