/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ADM_SprintChartsController {
    @RemoteAction
    global static String getCurrSprintPoints(String sprintId) {
        return null;
    }
    @RemoteAction
    global static List<agf__ADM_Sprint__c> getCurrSprints(String teamId) {
        return null;
    }
    @RemoteAction
    global static Integer getTotalSprints(String teamId) {
        return null;
    }
}
