/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ADM_Chatter {
    global ADM_Chatter() {

    }
    webService static String chatterValue(String parentId, String subscriberId) {
        return null;
    }
    webService static List<EntitySubscription> getSubscriptionsForParentId(String parentId, String subscriberId) {
        return null;
    }
    webService static Boolean isSubscribed(String parentId, String subscriberId) {
        return null;
    }
    webService static String toggleSubscription(String parentId, String subscriberId) {
        return null;
    }
}
