/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class ADM_AutoComplete2Controller {
    @RemoteAction
    global static List<agf__ADM_Scrum_Team__c> getAllTeams() {
        return null;
    }
    @RemoteAction
    global static List<User> getAllUsers() {
        return null;
    }
    @RemoteAction
    global static agf.ADM_AutoComplete2Controller.SearchResponse searchSuggestions(String text, String queryName, Map<String,String> params) {
        return null;
    }
global class SearchResponse {
    global SearchResponse() {

    }
}
}
