/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
global class RunTestGroupsBatch implements Database.AllowsCallouts, Database.Batchable<Id> {
    global RunTestGroupsBatch(List<Id> testGroupIds1) {

    }
    global void execute(Database.BatchableContext BC, List<Id> testGroupIdsBatch) {

    }
    global void finish(Database.BatchableContext BC) {

    }
    global List<Id> start(Database.BatchableContext BC) {
        return null;
    }
}
