/*
Este archivo se ha generado y no es el código fuente actual para esta
clase global gestionada.
Este archivo de solo lectura muestra los métodos, las variables, las propiedades
y los constructores globales de la clase.
Para permitir al código compilar, todos los métodos devuelven nulo.
*/
@RestResource(urlMapping='/SeleniumTestCaseViewEdit')
global class SeleniumTestCaseViewEdit {
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo getTestCaseInfo(Id TestCaseId) {
        return null;
    }
    @HttpGet
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseLoadAll() {
        return null;
    }
    @HttpPost
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseSaveAll(Id testCaseId, String versionString, String name, String testCaseSrc, String testDataSrc) {
        return null;
    }
    global static copado.SeleniumTestCaseViewEdit.TestCaseInfo testCaseSaveAllImpl(Id testCaseId, String versionString, String name, String testCaseSrc, String testDataSrc) {
        return null;
    }
global class TestCaseDatasets {
    global TestCaseDatasets() {

    }
}
global class TestCaseInfo {
    global TestCaseInfo() {

    }
}
global class TestCaseNameAndVersion {
    global TestCaseNameAndVersion() {

    }
}
}
